<?php

// copy to cache/lang_cache/master_lang/
$lang = array(
	'o_clients' => 'OAuth2 Applications',
	'o_client_name' => 'Name',
	'o_client_name_info' => 'Something users will recognize and trust',
	'o_client_url' => 'URL',
	'o_client_numusers' => 'Number of members',
	'o_no_clients' => 'No OAuth2 applications.',
	'o_new_client' => 'Create new OAuth2 Application',
	'o_update_client' => 'Update OAuth2 Application',
	'o_create' => 'Create Application',
	'o_update' => 'Update Application',
	'o_new_client_short' => 'New Application',
	'o_update_client_short' => 'Update Application',
	'o_client_id' => 'Client ID',
	'o_client_secret' => 'Client Secret',
	'o_info' => 'You may create OAuth2 clients so third-party applications can use IP.Board for authentication.',
	'o_redirect_uri' => 'Authorization callback URL',
	'o_redirect_uri_info' => 'Your application\'s callback URL',
	'o_homepage_uri' => 'Homepage URL',
	'o_homepage_uri_info' => 'The full URL to your application homepage',
	'o_homepage_description' => 'Application Description',
	'o_homepage_description_info' => 'This is displayed to all potential users of your application',
	'o_homepage_logo' => 'Homepage Logo URL',
	'o_homepage_logo_info' => 'An URL to the logo of your site, preferably in square size, at least 100x100.',
	'o_please_enter_name' => 'Please enter a name.',
	'o_no_id' => 'No Client ID submitted.',
	'o_no_secret' => 'No Client Secret submitted.',
	'o_created' => 'New OAuth2 Application has been successfully created.',
	'o_updated' => 'OAuth2 Application has been successfully updated.',
	'o_no_redirect' => 'You must enter an Authorization callback URL.',
	'o_no_logo' => 'You must provide a logo for your application.',
	'o_edit' => 'Edit',
	'o_delete' => 'Delete',
	'o_client404' => 'Could not find Application for given client_id.',
	'o_whatclient'=> 'You must provide a Client ID.',
	'o_deleted'=> 'Application has successfully been deleted.',
);